name: commit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Must be explicit for proper pipefail support
        shell: bash
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Python check
      run: python -m compileall -q .
