name: release-windows

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.tag_name }}

    - name: Install Python Deps
      run: pip3 install tk pyinstaller
    - name: Python check
      run: python -m compileall -q .
    - name: Build bingo watcher
      run: pyinstaller BingoDisplay.py --onefile --noconsole
    - name: dir dist
      run: dir dist

    - name: Upload Release Asset BingoDisplay.exe
      id: upload-release-asset-bingo
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/BingoDisplay.exe
        asset_name: BingoDisplay.exe
        asset_content_type: application/octet-stream
